In [1]:
# Final Project physics 140
# Created by Peter Nguyen 
# Prompt: Use reinforced learning and the bellman equation to train an agent to solve mazes.

In [2]:
# module imports
import numpy as np
import matplotlib.pyplot as plt
import random

In [3]:
# Creation of the graph

# Width of Graph
W = 6
# Length of Graph
L = 6
# edge
Edge = 0
# Area
A = W*L

# maze initializing
maze = np.zeros((W,L))
print(maze)
#maze[0,1] = 1
#maze[0,0] = 2

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
# define class of agent
class agent():
    # Default Constructor
    def __init__(self, name, pos_x = 0, pos_y = 0):
        self.name = name
        self.position_x = pos_x
        self.position_y = pos_y
        print("agent created:",name)
        
    def curr_position(self):
        return (self.position_x,self.position_y)
        
    # Movement method for our agent
    def movement(self, maze, move):
        #view_maze(maze)
        print("new movement made")
        # go down
        if move == 1:
            self.position_y+=1
            print("right")
        # go up
        elif move == 2:
            self.position_y-=1
            print("left")
        # move right
        elif move == 3:
            self.position_x+=1
            print("down")
        # move left
        elif move == 4:
            self.position_x-=1
            print("up")
            
            

In [5]:
# Test Agent
a1 = agent("Peter",1,1)

agent created: Peter


In [6]:
def view_maze(maze):
    print("   1  2  3")
    count = 0
    for i in maze:
        count+=1
        print(count,i)

In [7]:
# boundary checker + movement functionality

#start
print("start")

for i in range(100):
    x_pos, y_pos = a1.curr_position()
    print("x",x_pos + 1,"y",y_pos + 1)
    maze[x_pos,y_pos] = i + 1
    view_maze(maze)
    print('iter',i)
    move = np.random.randint(1,5)
    # Checks for boundaries in down
    if x_pos < W - 1 and move == 3:
        a1.movement(maze, move)
    # Checks for boundaries in up
    elif x_pos > Edge and move == 4:
        a1.movement(maze, move)
    #checks for boundaries in left
    elif y_pos < L - 1 and move == 1:
        a1.movement(maze, move)
    # Checks for boundaries in right
    elif y_pos > Edge and move == 2:
        a1.movement(maze, move)
    # indicate that the agent hit the boundary
    else:
        if move == 1:
            print("boundary hit on right")
        elif move == 2:
            print("boundary hit on left")
        elif move == 3:
            print("boundary hit on down")
        elif move == 4:
            print("boundary hit on up")
    print('---------- END OF TURN ---------------')

start
x 2 y 2
   1  2  3
1 [0. 0. 0. 0. 0. 0.]
2 [0. 1. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 0.]
6 [0. 0. 0. 0. 0. 0.]
iter 0
new movement made
left
---------- END OF TURN ---------------
x 2 y 1
   1  2  3
1 [0. 0. 0. 0. 0. 0.]
2 [2. 1. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 0.]
6 [0. 0. 0. 0. 0. 0.]
iter 1
new movement made
right
---------- END OF TURN ---------------
x 2 y 2
   1  2  3
1 [0. 0. 0. 0. 0. 0.]
2 [2. 3. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 0.]
6 [0. 0. 0. 0. 0. 0.]
iter 2
new movement made
left
---------- END OF TURN ---------------
x 2 y 1
   1  2  3
1 [0. 0. 0. 0. 0. 0.]
2 [4. 3. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0.]
5 [0. 0. 0. 0. 0. 0.]
6 [0. 0. 0. 0. 0. 0.]
iter 3
new movement made
right
---------- END OF TURN ---------------
x 2 y 2
   1  2  3
1 [0. 0. 0. 0. 0. 0.]
2 [4. 5. 0. 0. 0. 0.]
3 [0. 0. 0. 0. 0. 0.]
4 [0. 0. 0. 0. 0. 0.]
5 [0.

1 [11. 14. 13.  8.  0.  0.]
2 [ 4. 15.  6.  0.  0.  0.]
3 [21. 26. 23.  0.  0.  0.]
4 [43. 44. 47.  0.  0.  0.]
5 [39. 45. 48.  0.  0.  0.]
6 [34.  0.  0.  0.  0.  0.]
iter 47
new movement made
down
---------- END OF TURN ---------------
x 6 y 3
   1  2  3
1 [11. 14. 13.  8.  0.  0.]
2 [ 4. 15.  6.  0.  0.  0.]
3 [21. 26. 23.  0.  0.  0.]
4 [43. 44. 47.  0.  0.  0.]
5 [39. 45. 48.  0.  0.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 48
new movement made
up
---------- END OF TURN ---------------
x 5 y 3
   1  2  3
1 [11. 14. 13.  8.  0.  0.]
2 [ 4. 15.  6.  0.  0.  0.]
3 [21. 26. 23.  0.  0.  0.]
4 [43. 44. 47.  0.  0.  0.]
5 [39. 45. 50.  0.  0.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 49
new movement made
right
---------- END OF TURN ---------------
x 5 y 4
   1  2  3
1 [11. 14. 13.  8.  0.  0.]
2 [ 4. 15.  6.  0.  0.  0.]
3 [21. 26. 23.  0.  0.  0.]
4 [43. 44. 47.  0.  0.  0.]
5 [39. 45. 50. 51.  0.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 50
new movement made
right
---------- END OF TURN -------

iter 92
new movement made
right
---------- END OF TURN ---------------
x 2 y 4
   1  2  3
1 [63. 71. 76. 91. 88.  0.]
2 [61. 60. 93. 94. 89.  0.]
3 [21. 26. 68.  0.  0.  0.]
4 [43. 44. 57.  0.  0.  0.]
5 [39. 45. 56. 55. 52.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 93
new movement made
left
---------- END OF TURN ---------------
x 2 y 3
   1  2  3
1 [63. 71. 76. 91. 88.  0.]
2 [61. 60. 95. 94. 89.  0.]
3 [21. 26. 68.  0.  0.  0.]
4 [43. 44. 57.  0.  0.  0.]
5 [39. 45. 56. 55. 52.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 94
new movement made
right
---------- END OF TURN ---------------
x 2 y 4
   1  2  3
1 [63. 71. 76. 91. 88.  0.]
2 [61. 60. 95. 96. 89.  0.]
3 [21. 26. 68.  0.  0.  0.]
4 [43. 44. 57.  0.  0.  0.]
5 [39. 45. 56. 55. 52.  0.]
6 [34.  0. 49.  0.  0.  0.]
iter 95
new movement made
left
---------- END OF TURN ---------------
x 2 y 3
   1  2  3
1 [63. 71. 76. 91. 88.  0.]
2 [61. 60. 97. 96. 89.  0.]
3 [21. 26. 68.  0.  0.  0.]
4 [43. 44. 57.  0.  0.  0.]
5 [39. 45. 56. 55. 52.  0.

In [8]:
# Todo list:
# if -1 = wall, block path
# if 1 then ending
# Creation of the graph

# Width of Graph
W = 6
# Length of Graph
L = 6
# edge
Edge = 0

# maze initializing
maze = np.zeros((W,L))
print(maze)
#maze[0,1] = 1
#maze[0,0] = 2

# randomizer
for i in range(W):
    for j in range(L):
        if np.random.randint(0,10) < 3:
            maze[i,j] = -1
print(maze)
        

# end goal
maze[5,5] = 1

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0. -1. -1.]
 [-1. -1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.]
 [-1.  0.  0. -1. -1. -1.]]
