In [1]:
import numpy as np
import random

In [2]:
# Matrix generation functionality
# Width
W = 6
# Length
L = 6
# Area 
A = W*L

# For Maze Creation and q table pairing
def create_maze(width, length):
    maze = np.zeros((width, length), int)
    return maze

# Create Q-table
def create_Q_table(maze,width,length):
    q_table = np.zeros((width, length, 4))
    # boundary creation for walls in the Q-table
    for i in range(width):
        for j in range(length):
            if j = 0:
                # upper bound
                q_table[i,j,4] = None
            elif i = 0:
                # left bound
                q_table[]
                
    

# For Saving the maze
def save_maze(maze):
    np.save('maze4',maze)

# Load in maze from file
def load_maze(mazename):
    return np.load(mazename)

# View maze
def view_maze(maze):
    count = 0
    for i in maze:
        count+=1
        print(count,i)
        
# fill maze w obstacles
def fill_maze(maze, Width, Length):
    for i in range(Width):
        for j in range(Length):
            if np.random.randint(0,10) < 2:
                maze[i,j] = -100
    return maze



In [3]:
# define class of agent
class agent():
    # Default Constructor
    def __init__(self, name, pos_x = 0, pos_y = 0):
        self.name = name
        self.position_x = pos_x
        self.position_y = pos_y
        print("agent created:",name)
        
    def curr_position(self):
        return (self.position_x,self.position_y)
    
        
    # Movement method for our agent
    def movement(self, maze, move):
        #view_maze(maze)
        print("new movement made")
        
        # go right
        if move == 1 and maze[self.position_x,self.position_y+1]!=-1:
            self.position_y+=1
            print("right")
        # go left
        elif move == 2 and maze[self.position_x,self.position_y-1]!=-1:
            self.position_y-=1
            print("left")
        # move down
        elif move == 3 and maze[self.position_x+1,self.position_y]!=-1:
            self.position_x+=1
            print("down")
        # move up
        elif move == 4 and maze[self.position_x-1,self.position_y]!=-1:
            self.position_x-=1
            print("up")
        else:
            print("hit a boulder")
            
            

In [4]:
def isGameOver(cur_x, cur_y):
    if cur_x == 4 && cur_y == 4:
        return True

SyntaxError: invalid syntax (<ipython-input-4-267e12b0b670>, line 2)

In [5]:
# actual maze creation
maze, q_table = create_maze(6,6)
maze = fill_maze(maze,6,6)
save_maze(maze)

In [6]:
# set percent that you want to explore
epsilon = 0.2
discount = 0.9
learning_rate = 0.1

In [7]:
maze = load_maze("maze4.npy")
# view_maze(maze) # environment matrix

In [8]:
# main function/loop
# winning spot was (4,4)

# Exploration rate vs exploitation rate, higher the epsilon value, the more exploration will occur
epsilon = 0.2
for i in range(100):
    # start off at our random position
    cur_x = random.randint(0,W)
    cur_y = random.randint(0,L)
    #print(i,cur_x,cur_y)
    
    # resets the maze along with the goal point
    maze = load_maze("maze4.npy")
    maze[4,4] = 100
    
    
print(maze)
    
    

[[   0    0 -100    0    0 -100]
 [-100    0    0    0    0    0]
 [   0 -100 -100 -100    0    0]
 [   0    0    0    0    0 -100]
 [   0    0    0    0  100    0]
 [   0    0    0    0 -100    0]]


In [ ]:
print(q_table[0,5,0]) # x, y coord, action value
print(q_table)