In [1]:
# Testing Page

In [2]:
# module imports
import numpy as np
import matplotlib.pyplot as plt
import random

In [3]:
# Creation of the graph

# Width of Graph
W = 6
# Length of Graph
L = 6
# edge
Edge = 0
# Area
A = W*L

# maze initializing
maze = np.zeros((W,L), int)
print(maze)
#maze[0,1] = 1
#maze[0,0] = 2

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [4]:
# Todo list:
# if -1 = wall, block path
# if 1 then ending
# Creation of the graph

# Width of Graph
W = 6
# Length of Graph
L = 6
# edge
Edge = 0

# maze initializing
maze = np.zeros((W,L), int)
print(maze)
print()
#maze[0,1] = 1
#maze[0,0] = 2

# randomizer
for i in range(W):
    for j in range(L):
        if np.random.randint(0,10) < 2:
            maze[i,j] = -1


#maze = [[-1, 0, 0, 0, 0, 0],[-1, 0, 0, 0, 0, 0],[-1, -1, -1, 0, 0, 0],[0, 0, 0, 0, 0, -1],[0, 1, 0, -1, 0, 0],[-1, 0, 0, 0, -1, 0]]



print()
        

# end goal
# maze[5,5] = 1
print(maze)
# contains the end goal
win_x = 0
win_y = 0
maze[win_x,win_y] = 1

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


[[ 0  0  0  0  0  0]
 [ 0 -1  0  0  0  0]
 [ 0  0  0  0  0 -1]
 [ 0  0  0  0  0  0]
 [ 0 -1  0 -1  0  0]
 [ 0  0  0 -1  0  0]]


In [12]:
# saving and loading of maze
np.save('maze2',maze)

In [11]:
# load in maze 
maze = np.load('maze2.npy')


ValueError: Cannot load file containing pickled data when allow_pickle=False

In [5]:
# define class of agent
class agent():
    # Default Constructor
    def __init__(self, name, pos_x = 0, pos_y = 0):
        self.name = name
        self.position_x = pos_x
        self.position_y = pos_y
        print("agent created:",name)
        
    def curr_position(self):
        return (self.position_x,self.position_y)
    
        
    # Movement method for our agent
    def movement(self, maze, move):
        #view_maze(maze)
        print("new movement made")
        
        # go down
        if move == 1 and maze[self.position_x,self.position_y+1]!=-1:
            self.position_y+=1
            print("right")
        # go up
        elif move == 2 and maze[self.position_x,self.position_y-1]!=-1:
            self.position_y-=1
            print("left")
        # move right
        elif move == 3 and maze[self.position_x+1,self.position_y]!=-1:
            self.position_x+=1
            print("down")
        # move left
        elif move == 4 and maze[self.position_x-1,self.position_y]!=-1:
            self.position_x-=1
            print("up")
        else:
            print("hit a wall")
            
            

In [6]:
# Test Agent
a1 = agent("Peter",2,2)

agent created: Peter


In [7]:
def view_maze(maze):
    print("   1  2  3")
    count = 0
    for i in maze:
        count+=1
        print(count,i)

In [8]:
# boundary checker + movement functionality

#start
print("start")

for i in range(100):
    x_pos, y_pos = a1.curr_position()
    if x_pos == win_x and y_pos == win_y:
        print("Goal reached")
        break
    print("x",x_pos + 1,"y",y_pos + 1)
    maze[x_pos,y_pos] = i + 101
    view_maze(maze)
    print('iter',i)
    move = np.random.randint(1,5)
    # Checks for boundaries in down
    if x_pos < W - 1 and move == 3:
        a1.movement(maze, move)
        
    # Checks for boundaries in up
    elif x_pos > Edge and move == 4:
        a1.movement(maze, move)
    #checks for boundaries in left
    elif y_pos < L - 1 and move == 1:
        a1.movement(maze, move)
    # Checks for boundaries in right
    elif y_pos > Edge and move == 2:
        a1.movement(maze, move)
    # indicate that the agent hit the boundary
    else:
        if move == 1:
            print("boundary hit on right")
        elif move == 2:
            print("boundary hit on left")
        elif move == 3:
            print("boundary hit on down")
        elif move == 4:
            print("boundary hit on up")
    print('---------- END OF TURN ---------------')

start
x 3 y 3
   1  2  3
1 [1 0 0 0 0 0]
2 [ 0 -1  0  0  0  0]
3 [  0   0 101   0   0  -1]
4 [0 0 0 0 0 0]
5 [ 0 -1  0 -1  0  0]
6 [ 0  0  0 -1  0  0]
iter 0
new movement made
up
---------- END OF TURN ---------------
x 2 y 3
   1  2  3
1 [1 0 0 0 0 0]
2 [  0  -1 102   0   0   0]
3 [  0   0 101   0   0  -1]
4 [0 0 0 0 0 0]
5 [ 0 -1  0 -1  0  0]
6 [ 0  0  0 -1  0  0]
iter 1
new movement made
hit a wall
---------- END OF TURN ---------------
x 2 y 3
   1  2  3
1 [1 0 0 0 0 0]
2 [  0  -1 103   0   0   0]
3 [  0   0 101   0   0  -1]
4 [0 0 0 0 0 0]
5 [ 0 -1  0 -1  0  0]
6 [ 0  0  0 -1  0  0]
iter 2
new movement made
right
---------- END OF TURN ---------------
x 2 y 4
   1  2  3
1 [1 0 0 0 0 0]
2 [  0  -1 103 104   0   0]
3 [  0   0 101   0   0  -1]
4 [0 0 0 0 0 0]
5 [ 0 -1  0 -1  0  0]
6 [ 0  0  0 -1  0  0]
iter 3
new movement made
up
---------- END OF TURN ---------------
x 1 y 4
   1  2  3
1 [  1   0   0 105   0   0]
2 [  0  -1 103 104   0   0]
3 [  0   0 101   0   0  -1]
4 [0 0 0 0 0 0

In [9]:
# Difference between main and this is collision boundaries